### ISSUE TITLE
Requests sent to server contain a null session field.

### ISSUE THREAD

**Issue by bogdan-vld** [npr/RAD-Android#17]
**Describe the Bug**
The audio sessions array in the json body of a request made to the server sometimes contains an extra _null_ element

**To Reproduce**
1. Instantiate RAD framework
2. Configure RAD framework with following parameters:
sessionExpirationTime = 1;
batchSize = 3
3. Play media file that has a RAD metadata and report 3 events (or the batchSize from the previous step)

**Actual Behavior**
There should be no _null_ atributes in the request body

**Expected Behavior**
There is one extra element in the audioSessions array that reads _null_

**Comment by dmacra** [comment]
Fixed starting with v1.0.9
