### ISSUE TITLE
Remove application android:allowBackup="true" or set it to false.

### ISSUE THREAD

**Issue by allenbaker** [npr/RAD-Android#6]
**Describe the Bug**
<application android:allowBackup="true"> in the manifest is resulting in an error when we try to run NPR One with the RAD library with a *Manifest merger failed* error. Can this line please be removed or at a minimum set to false?

**To Reproduce**
1. implement the RAD framework in a projects build.gradle
2. Try to run the project

**Comment by bogdan-vld** [comment]
Fixed in version 1.0.4.

**Comment by allenbaker** [comment]
Thank you for the prompt response @bogdan-vld. I looked at the merge for master and I saw you removed the line from `demo/src/main/AndroidManifest.xml` but not `/rad/src/main/AndroidManifest.xml`.  Can you please remove that line from the manifest there or set it to false?

**Comment by bogdan-vld** [comment]
Really embarrassed I missed this! Pushed 1.0.5.

**Comment by allenbaker** [comment]
No worries at all, looks good now. Thanks!
